name: ETC Frontend E2E Tests

on: push

jobs:
  run-etc-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Test frontend using Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Test frontend using Edge
        uses: cypress-io/github-action@v6
        with:
          browser: edge